### PR TITLE
Finished basic server implementation

### PR DESCRIPTION
**Pull request by Huntrr**

### CODE REVIEW

**Comment by LewisJEllis** [comment]
You shouldn't keep your node_modules folder under source control unless you have a specific reason to. That's what package.json and `npm install` are for.

**Comment by Huntrr** [comment]
@LewisJEllis I'm aware of best practice for actual applications. I left it in here, however, so the whole application+dependencies can be downloaded at once, for those who don't know what they're doing.

But, given that it's really just one extra command, I can see a good argument for either way. If someone else agrees with you that it's not worth the slight convenience gain, we can drop it.

**Comment by LewisJEllis** [comment]
Those who don't know what they're doing won't know how to run the server anyway.

If your concern is convenience and accessibility to people not familiar with npm, a makefile and a readme can address that much more effectively than leaving your dependencies in the repo. Since this project is for educational purposes, you might as well teach and demonstrate best practices.

**Comment by Huntrr** [comment]
> Since this project is for educational purposes, you might as well teach and demonstrate best practices

Fair point. #2

**Pull request merged**
